services:
  - type: web
    name: creatorhub
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: dpg-d6q6pr8gjchc738okpa0-a.oregon-postgres.render.com
      - key: DB_USER
        value: creator_user
      - key: DB_PASS
        value: kg8fs00oQ87q1VpTh1zYXcRf6bknVH7C
      - key: DB_NAME
        value: creator_platform_16ux
      - key: URLROOT
        fromService:
          type: web
          name: creatorhub
          property: host
      - key: MPESA_CONSUMER_KEY
        value: YOUR_MPESA_CONSUMER_KEY_HERE
      - key: MPESA_CONSUMER_SECRET
        value: YOUR_MPESA_CONSUMER_SECRET_HERE